"""Obtain the deduction-extended database from cinderhaven-data.

The canonical deduction dataset is now generated by the cinderhaven-data
repo (https://github.com/MsShawnP/cinderhaven-data). This script copies
the built database into this project's data/ directory so the JSON export
and validator can run against it.

Usage:
  python scripts/build_deductions_db.py           # copy if target missing
  python scripts/build_deductions_db.py --force   # overwrite existing copy
  python scripts/build_deductions_db.py --build   # build cinderhaven-data first, then copy

Expects cinderhaven-data as a sibling directory (../cinderhaven-data/).
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"

CINDERHAVEN_DATA_REPO = ROOT.parent / "cinderhaven-data"
SOURCE_DB = CINDERHAVEN_DATA_REPO / "data" / "cinderhaven_product_master.db"
TARGET_DB = DATA / "cinderhaven_deductions.db"


def ensure_source_exists(do_build: bool) -> None:
    if SOURCE_DB.exists():
        return

    if not CINDERHAVEN_DATA_REPO.exists():
        sys.exit(
            f"cinderhaven-data repo not found at {CINDERHAVEN_DATA_REPO}.\n"
            f"Clone https://github.com/MsShawnP/cinderhaven-data as a sibling directory."
        )

    if not do_build:
        sys.exit(
            f"Built database not found at {SOURCE_DB}.\n"
            f"Run `python scripts/build_db.py --force` in cinderhaven-data first,\n"
            f"or pass --build to have this script do it."
        )

    print("Building cinderhaven-data database...")
    build_script = CINDERHAVEN_DATA_REPO / "scripts" / "build_db.py"
    result = subprocess.run(
        [sys.executable, str(build_script), "--force"],
        cwd=CINDERHAVEN_DATA_REPO,
    )
    if result.returncode != 0:
        sys.exit(f"cinderhaven-data build failed (exit {result.returncode}).")


def copy_db() -> None:
    DATA.mkdir(exist_ok=True)
    if TARGET_DB.exists():
        TARGET_DB.unlink()
    shutil.copy2(SOURCE_DB, TARGET_DB)
    size_mb = TARGET_DB.stat().st_size / (1024 * 1024)
    print(f"  [OK] Copied {SOURCE_DB.name} -> {TARGET_DB.name} ({size_mb:.1f} MB)")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Copy the built cinderhaven-data database for local JSON export."
    )
    parser.add_argument(
        "--force", action="store_true",
        help="Overwrite target DB even if it already exists",
    )
    parser.add_argument(
        "--build", action="store_true",
        help="Build cinderhaven-data from scratch before copying",
    )
    args = parser.parse_args()

    if TARGET_DB.exists() and not args.force and not args.build:
        size_mb = TARGET_DB.stat().st_size / (1024 * 1024)
        print(f"Target DB already exists ({size_mb:.1f} MB). Use --force to re-copy.")
        return

    ensure_source_exists(do_build=args.build)
    copy_db()
    print(f"\nDone. Run the JSON export next:\n  python scripts/20_export_json.py")


if __name__ == "__main__":
    main()
